if "%DATE:~5,2%"=="1/" set "MMM=January"
if "%DATE:~5,2%"=="2/" set "MMM=February"
if "%DATE:~5,2%"=="3/" set "MMM=March"
if "%DATE:~5,2%"=="4/" set "MMM=April"
if "%DATE:~5,2%"=="5/" set "MMM=May"
if "%DATE:~5,2%"=="6/" set "MMM=June"
if "%DATE:~5,2%"=="7/" set "MMM=July"
if "%DATE:~5,2%"=="8/" set "MMM=August"
if "%DATE:~5,2%"=="9/" set "MMM=September"
if "%DATE:~5,2%"=="10" set "MMM=October"
if "%DATE:~5,2%"=="11" set "MMM=November"
if "%DATE:~5,2%"=="12" set "MMM=December"
set "YYYY=%DATE:~10,4%"

bitsadmin.exe /transfer "NPI download" http://nppes.viva-it.com/NPPES_Data_Dissemination_%MMM%_%YYYY%.zip C:\NPPES_Data_Dissemination_%MMM%_%YYYY%.zip
